from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent
SRC = ROOT / "src"
if str(SRC) not in sys.path:
    sys.path.insert(0, str(SRC))

from quantmarket_market.config import QUANTSERVICE_HANDOFF_DIR

REQUIRED_FILES = {
    "quantservice_market_home.json": ["market", "asof", "hero", "top_signals", "consumer_slots"],
    "quantservice_market_today.json": ["market", "asof", "market_bridge", "consumer_slots"],
    "quantservice_market_page.json": ["market", "asof", "header_state", "component_cards", "signal_lists", "consumer_slots"],
    "quantservice_market_manifest.json": ["market", "asof", "generated_by", "consumer", "files", "slot_files"],
    "api_v1_market_analysis_home.json": ["api_version", "endpoint", "market", "asof", "generated_by", "data"],
    "api_v1_market_analysis_page.json": ["api_version", "endpoint", "market", "asof", "generated_by", "data"],
    "api_v1_market_analysis_summary.json": ["api_version", "endpoint", "market", "asof", "generated_by", "data"],
    "api_v1_market_analysis_detail.json": ["api_version", "endpoint", "market", "asof", "generated_by", "data"],
    "api_v1_market_analysis_today_bridge.json": ["api_version", "endpoint", "market", "asof", "generated_by", "data"],
}


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Validate QuantService handoff artifacts generated by QuantMarket.")
    parser.add_argument("--handoff-dir", default=str(QUANTSERVICE_HANDOFF_DIR), help="Handoff directory to validate.")
    return parser.parse_args()


def _load_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8-sig"))


def validate_quantservice_handoff(handoff_dir: Path) -> dict:
    errors: list[str] = []
    if not handoff_dir.exists():
        return {
            "ok": False,
            "handoff_dir": str(handoff_dir),
            "errors": [f"handoff directory does not exist: {handoff_dir}"],
        }

    payloads: dict[str, dict] = {}
    for filename, required_keys in REQUIRED_FILES.items():
        path = handoff_dir / filename
        if not path.exists():
            errors.append(f"missing handoff file: {path}")
            continue
        try:
            payload = _load_json(path)
        except Exception as exc:
            errors.append(f"{filename}: invalid json: {type(exc).__name__}: {exc}")
            continue
        payloads[filename] = payload
        for key in required_keys:
            if key not in payload:
                errors.append(f"{filename}: missing required key '{key}'")

    asof_values = {payload.get("asof") for payload in payloads.values() if payload.get("asof")}
    market_values = {payload.get("market") for payload in payloads.values() if payload.get("market")}
    if len(asof_values) != 1:
        errors.append(f"inconsistent asof values: {sorted(asof_values)}")
    if len(market_values) != 1:
        errors.append(f"inconsistent market values: {sorted(market_values)}")

    manifest = payloads.get("quantservice_market_manifest.json") or {}
    files = manifest.get("files") or {}
    for key, filename in files.items():
        target = handoff_dir / filename
        if not target.exists():
            errors.append(f"manifest file mapping missing target: {key} -> {filename}")

    return {
        "ok": not errors,
        "handoff_dir": str(handoff_dir),
        "market": next(iter(market_values)) if len(market_values) == 1 else None,
        "asof": next(iter(asof_values)) if len(asof_values) == 1 else None,
        "validated_files": sorted(REQUIRED_FILES),
        "slot_count": len(manifest.get("slot_files") or {}),
        "errors": errors,
    }


def main() -> None:
    args = parse_args()
    result = validate_quantservice_handoff(Path(args.handoff_dir))
    print(json.dumps(result, ensure_ascii=False, indent=2))
    if not result["ok"]:
        sys.exit(1)


if __name__ == "__main__":
    main()
